#!/usr/bin/python3

from pytest import skip

# Function: SMF
# Source: 33515-g40.md
# Section: 4.2.2.1.4
# Title: Charging ID Uniqueness
# Purpose:
# Verify that the charging ID generated by the SMF for each PDU session is unique.
#
# Execution Steps:
# ----------------
# 1. The tester intercepts the traffic between the SMF under test and the CHF.
# 2. The tester triggers the establishment of the maximum number of concurrent PDU sessions that
# the SMF under test can handle.
# 3. The tester captures each Charging Data Request [initial] sent from the SMF under test to the
# CHF, and verifies the charging ID contained in the 'PDU Session Charging Information' IE in each
# Charging Data Request [initial] is unique.
#
# Expected Results:
# ----------------
# The charging ID in each Charging Data Request [initial] is unique.


def test_33515_g40_TC_CHARGING_ID_UNIQUENESS_SMF():
    skip('Not implemented...')
