#!/usr/bin/python3

from pytest import skip

# Function: General
# Source: 33117-g80.md
# Section: 4.3.2.3
# Title: No unused software
# Purpose:
# To ensure that there is no unused software or associated components that might be installed in
# the network product which are not required for its operation or functionality.
#
# Execution Steps:
# ----------------
# The accredited evaluator's test lab is required to execute the following steps:
# 1. Verification of the compliance to the prerequisites:
# a. Verification that the list of software / libraries and components is available in the
# documentation of the Network Product.
# b. Validation that all entries in the list of software / libraries and components are meaningful
# and reasonably necessary for the operation of the Network Product class.
# 2. Identification of the software / libraries or components which are installed in the system
# using any suitable command line tools or any other suitable means of determination.
# 3. Validation that there are no entries in the list of software / libraries installed in the
# system apart from the ones that have been mentioned and deemed necessary for the operation of the
# network product in the attached documentation.
# 4. Based on his/her experience, the tester will check for known default example files for
# software installed on the system.
#
# Expected Results:
# ----------------
# The report will contain the names and version of the tool(s) used for finding out what software /
# libraries is installed in the system. The detailed report will contain the name and version
# information of all the software / libraries installed in the system generated by the tool.
# The list of all available software / libraries which has been deemed necessary for the operation
# of the network product by the vendor shall also be included as the test result. Any software /
# library not in the list of allowed software / libraries will be highlighted and brought out as a
# part of the report.
# There should be no unnecessary software / library installed in the network product except for the
# ones which are deemed necessary for its operation.
# There should be no more default example files for the installed software on the system.


def test_33117_g80_TC_NO_UNUSED_SOFTWARE():
    skip('Not implemented...')
