#!/usr/bin/python3

from pytest import skip

# Function: General
# Source: 33117-g80.md
# Section: 4.3.2.4
# Title: No unused functions
# Purpose:
# To ensure that there is no unused hardware or software functions that are not deactivated in the
# network product which are not required for its operation or functionality.
#
# Execution Steps:
# ----------------
# The accredited evaluator's test lab is required to execute the following steps:
# 1. Identification of the hardware and software functions which are installed in the system or
# might have been disabled using any suitable command line tools or any other suitable means of
# determination.
# 2. Validate that there are no entries in the list of hardware and software functions installed in
# the system apart from the ones that have been mentioned and deemed necessary for the operation of
# the network product in the attached documentation.
#
# Expected Results:
# ----------------
# The report will contain the names and version of the tool(s) used for finding out what software
# and associated function is installed in the system. The detailed report will contain the name and
# version information of all the software and components installed in the system generated by the
# test tool.
# The list of all available software which has been deemed necessary for the operation of the
# network product by the vendor shall also be included as the test result. Any software not in the
# list of allowed software will be highlighted and brought out as a part of the report.
# There should be no unused function that is not deactivated in the network product except for the
# ones which are deemed necessary for its operation.


def test_33117_g80_TC_NO_UNUSED_FUNCTIONS():
    skip('Not implemented...')
