#!/usr/bin/python3

from pytest import skip

# Function: UPF
# Source: 33513-g20.md
# Section: 4.2.2.6
# Title: TEID uniqueness
# Purpose:
# Verify that the TEID generated by UPF under test for each new GTP tunnel is unique.
#
# Execution Steps:
# ----------------
# 1. The tester intercepts the traffic between the UPF under test and the SMF.
# 2. The tester triggers the maximum number of concurrent N4 session establishment requests.
# 3. The tester captures the N4 session establishment responses sent from UPF to SMF and verifies
#       that the F-TEID created for each generated response is unique.
#
# Expected Results:
# ----------------
# The F-TEID set in each different N4 session establishment response is unique.


def test_33513_g20_TC_TEID_ID_UNIQUENESS_UPF():
    skip('Not implemented...')
